spring.application.name=ai-trip-planner

spring.profiles.active=local

spring.datasource.url= jdbc:postgresql://localhost:5432/ai-trip-planner
spring.datasource.username=postgres


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true


spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

gemini.api.key=${GEMINI_API_KEY:}
gemini.model=gemini-2.5-flash

