spring.datasource.password=newpassword

# JWT Configuration - Strong & Correct
app.jwt.secret=SGVsbG9UaGlzSXNBVmVyeVN0cm9uZ0tleUZvckFJVHJpcFBsYW5uZXJBcHAgMjAyNg==
app.jwt.expiration-ms=86400000

# gemini.api.key=AIzaSyD-VvCVLwkmGqsZKH9vSkWwCZsZMrdugpU
# gemini.model=gemini-2.0-flash